#!/usr/bin/env bash

#set -x # Enable debugging

startDirectory=$(dirname "$(realpath "$0")")
[[ $startDirectory != $(pwd) ]] && echo "Run script from it's own directory" && exit 1

directories=(non-responsive responsive)

for directory in "${directories[@]}"; do
    cd "$directory" || exit

    [[ $directory == "responsive" ]] && mixinArgument="''"

    for file in _*.scss; do
	newFile="${file:1}"
	moduleName="${newFile/.scss/}"
	newFile="${newFile/.scss/-module.scss}"

	touch "$newFile"
	cat << EOF > "$newFile"
@use './$moduleName';

@include $moduleName.$moduleName($mixinArgument);
EOF
    done

    cd "$startDirectory" || exit
done
