#!/usr/bin/env bash

for file in _*; do
    newFile="${file:1}"
    baseName="${newFile/.scss/}"
    newFile="${newFile/.scss/-base.scss}"

    touch "$newFile"
    cat << EOF > "$newFile"
@use '../../functions';
@use '../../variables';
@use './$baseName';

@include $baseName.$baseName('');
EOF
done
